export const MATERIALS_SAVE_CREATE = 'MATERIALS_SAVE_CREATE';

export const MATERIALS_SAVE_CREATE_PARAMS = 'MATERIALS_SAVE_CREATE_PARAMS';

export const MATERIALS_INIT_CREATE_PARAMS = 'MATERIALS_INIT_CREATE_PARAMS';

export const MATERIALS_SAVE_TABLE = 'MATERIALS_SAVE_TABLE';

export const MATERIALS_SAVE_SEARCH_PARAMS = 'MATERIALS_SAVE_SEARCH_PARAMS';
